// Deterministic, realistic seed fixture for lead discovery (the "rented universe").
// Generated by index (NO Math.random) so tests are stable. Permanent dev/test
// fixture — CI never hits a paid API. ~40 companies / ~200 people / ~30 local.

import type {
  CompanyMatch,
  Department,
  Industry,
  LocalCategory,
  LocalMatch,
  PersonMatch,
  Seniority,
  SizeBand,
} from './types.js';

/** Cyclic pick that returns T (never undefined) for non-empty arrays. */
function cyc<T>(arr: readonly T[], i: number): T {
  const v = arr[((i % arr.length) + arr.length) % arr.length];
  if (v === undefined) throw new Error('cyc: empty array');
  return v;
}

const INDUSTRIES: Industry[] = [
  'saas',
  'fintech',
  'healthcare',
  'ecommerce',
  'manufacturing',
  'agency',
  'edtech',
  'biotech',
  'logistics',
  'real_estate',
];
const SIZES: SizeBand[] = ['1-10', '11-50', '51-200', '201-500', '501-1000', '1001-5000', '5000+'];
const EMPLOYEES: Record<SizeBand, number> = {
  '1-10': 6,
  '11-50': 30,
  '51-200': 120,
  '201-500': 350,
  '501-1000': 750,
  '1001-5000': 2500,
  '5000+': 8000,
};
const PLACES: { location: string; country: string }[] = [
  { location: 'San Francisco', country: 'US' },
  { location: 'New York', country: 'US' },
  { location: 'Austin', country: 'US' },
  { location: 'London', country: 'UK' },
  { location: 'Berlin', country: 'DE' },
  { location: 'Paris', country: 'FR' },
  { location: 'Amsterdam', country: 'NL' },
  { location: 'Toronto', country: 'CA' },
  { location: 'Singapore', country: 'SG' },
  { location: 'Sydney', country: 'AU' },
  { location: 'Bangalore', country: 'IN' },
  { location: 'Tokyo', country: 'JP' },
];
const CO_PREFIX = [
  'Nimbus',
  'Vertex',
  'Quanta',
  'Lumen',
  'Apex',
  'Northwind',
  'Cobalt',
  'Harbor',
  'Pinnacle',
  'Cedar',
  'Atlas',
  'Orbit',
  'Cascade',
  'Beacon',
  'Forge',
  'Summit',
  'Delta',
  'Ember',
  'Vega',
  'Onyx',
];
const CO_SUFFIX = [
  'Labs',
  'Systems',
  'Health',
  'Commerce',
  'Works',
  'Agency',
  'Learning',
  'Bio',
  'Logistics',
  'Realty',
];
const FIRST = [
  'Alex',
  'Jordan',
  'Sam',
  'Taylor',
  'Morgan',
  'Priya',
  'Wei',
  'Maria',
  'Liam',
  'Noah',
  'Olivia',
  'Emma',
  'Hiro',
  'Sofia',
  'Omar',
  'Chen',
  'Ava',
  'Lucas',
  'Mia',
  'Ethan',
];
const LAST = [
  'Chen',
  'Patel',
  'Garcia',
  'Smith',
  'Müller',
  'Kim',
  'Rossi',
  'Dubois',
  'Nguyen',
  'Johnson',
  'Silva',
  'Khan',
  'Tanaka',
  'Brown',
  'Lopez',
  'Wang',
  'Okafor',
  'Cohen',
  'Schmidt',
  'Ivanov',
];
const SENIORITIES: Seniority[] = ['c_level', 'vp', 'director', 'manager', 'senior', 'mid', 'entry'];
const DEPARTMENTS: Department[] = [
  'engineering',
  'sales',
  'marketing',
  'product',
  'finance',
  'operations',
  'hr',
  'legal',
  'support',
  'other',
];
const LOCAL_CATEGORIES: LocalCategory[] = [
  'restaurant',
  'dentist',
  'gym',
  'salon',
  'law_firm',
  'cafe',
  'auto_repair',
  'real_estate_agency',
];
const LOCAL_PREFIX = [
  'Sunrise',
  'Downtown',
  'Maple',
  'Riverside',
  'Golden',
  'Urban',
  'Elm Street',
  'Harbor',
  'Greenfield',
  'Lakeside',
];

const pad = (n: number) => String(n).padStart(4, '0');
const deptLabel = (d: Department) => d.charAt(0).toUpperCase() + d.slice(1);
const ROLE_WORD: Record<Department, string> = {
  engineering: 'Engineer',
  sales: 'Account Executive',
  marketing: 'Marketing Specialist',
  product: 'Product Manager',
  finance: 'Analyst',
  operations: 'Operations Specialist',
  hr: 'Recruiter',
  legal: 'Counsel',
  support: 'Support Specialist',
  other: 'Specialist',
};
const C_LEVEL_TITLE: Record<Department, string> = {
  engineering: 'CTO',
  finance: 'CFO',
  sales: 'CRO',
  operations: 'COO',
  product: 'Chief Product Officer',
  marketing: 'CMO',
  hr: 'Chief People Officer',
  legal: 'General Counsel',
  support: 'VP of Customer Success',
  other: 'Founder & CEO',
};

function titleFor(seniority: Seniority, dept: Department): string {
  switch (seniority) {
    case 'c_level':
      return C_LEVEL_TITLE[dept];
    case 'vp':
      return `VP of ${deptLabel(dept)}`;
    case 'director':
      return `Director of ${deptLabel(dept)}`;
    case 'manager':
      return `${deptLabel(dept)} Manager`;
    case 'senior':
      return `Senior ${ROLE_WORD[dept]}`;
    case 'mid':
      return ROLE_WORD[dept];
    case 'entry':
      return `${ROLE_WORD[dept]} Associate`;
  }
}

function buildCompanies(): CompanyMatch[] {
  const out: CompanyMatch[] = [];
  for (let i = 0; i < 40; i++) {
    const industry = cyc(INDUSTRIES, i);
    const sizeBand = cyc(SIZES, i);
    const place = cyc(PLACES, i);
    const name = `${cyc(CO_PREFIX, i)} ${cyc(CO_SUFFIX, i)}`;
    const domain = `${name.toLowerCase().replace(/[^a-z0-9]+/g, '')}.com`;
    out.push({
      externalId: `seed:company:${pad(i)}`,
      name,
      domain,
      industry,
      sizeBand,
      employeeCount: EMPLOYEES[sizeBand],
      location: place.location,
      country: place.country,
      linkedinUrl: `https://linkedin.com/company/${name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}`,
    });
  }
  return out;
}

function buildPeople(companies: CompanyMatch[]): PersonMatch[] {
  const out: PersonMatch[] = [];
  for (let j = 0; j < 200; j++) {
    const company = cyc(companies, j);
    const seniority = cyc(SENIORITIES, j);
    const department = cyc(DEPARTMENTS, j * 3 + 1); // decorrelate from seniority
    const firstName = cyc(FIRST, j);
    const lastName = cyc(LAST, j * 2 + 1);
    const fullName = `${firstName} ${lastName}`;
    const place = cyc(PLACES, j); // person location independent of company (remote)
    out.push({
      externalId: `seed:person:${pad(j)}`,
      firstName,
      lastName,
      fullName,
      email: `${firstName}.${lastName}@${company.domain}`.toLowerCase(),
      title: titleFor(seniority, department),
      seniority,
      department,
      companyExternalId: company.externalId,
      companyName: company.name,
      companyIndustry: company.industry,
      companySize: company.sizeBand,
      location: place.location,
      country: place.country,
      linkedinUrl: `https://linkedin.com/in/${fullName.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${pad(j)}`,
    });
  }
  return out;
}

function buildLocal(): LocalMatch[] {
  const out: LocalMatch[] = [];
  for (let k = 0; k < 30; k++) {
    const category = cyc(LOCAL_CATEGORIES, k);
    const place = cyc(PLACES, k);
    const label = category.replace(/_/g, ' ');
    const name = `${cyc(LOCAL_PREFIX, k)} ${label.replace(/\b\w/g, (c) => c.toUpperCase())}`;
    out.push({
      externalId: `seed:local:${pad(k)}`,
      name,
      category,
      phone: `+1-555-0${pad(k)}`,
      address: `${100 + k} Main St`,
      city: place.location,
      country: place.country,
      website: `https://${name.toLowerCase().replace(/[^a-z0-9]+/g, '')}.example`,
      googleMapsUrl: `https://maps.example/${pad(k)}`,
      rating: Math.round((3.5 + (k % 15) / 10) * 10) / 10,
    });
  }
  return out;
}

export const SEED_COMPANIES: CompanyMatch[] = buildCompanies();
export const SEED_PEOPLE: PersonMatch[] = buildPeople(SEED_COMPANIES);
export const SEED_LOCAL: LocalMatch[] = buildLocal();
